@baseUrl = https://8080-davidmarqss-tarefaapi-59rm02etfm2.ws-us115.gitpod.io
 
###
GET {{baseUrl}}/tarefa
 
###
POST {{baseUrl}}/tarefa
Content-Type: application/json
 
{
    "descricao": "Descrição 2",
    "concluido": true
}
 
###
GET {{baseUrl}}/tarefa/2
 
###
PUT {{baseUrl}}/tarefa/1
Content-Type: application/json
 
{
    "descricao": "Descrição 1",
    "concluido": false
}
 
###
DELETE {{baseUrl}}/tarefa/3