@baseUrl = https://8080-davidmarqss-apijava-6o9o4ang5m1.ws-us115.gitpod.io
 
###
GET {{baseUrl}}/tarefa
 
###
POST {{baseUrl}}/tarefa
Content-Type: application/json
 
{
    "descricao": "Descrição 1",
    "concluido": false
}
 
###
GET {{baseUrl}}/tarefa/2
 
###
PUT {{baseUrl}}/tarefa/2
Content-Type: application/json
 
{
    "descricao": "Descrição 1",
    "concluido": false
}
 
###
DELETE {{baseUrl}}/tarefa/3